CREATE TABLE Empleados
( 
	CodEmp               NUMBER NOT NULL ,
	DniEmp               NVARCHAR2(08)  NULL ,
	NomEmp               NVARCHAR2(60)  NULL ,
	ApeEmp               NVARCHAR2(60)  NULL ,
	EmailEmp             NVARCHAR2(50)  NULL ,
	CelEmp               NVARCHAR2(09)  NULL ,
	DirecEmp             NVARCHAR2(60)  NULL ,
	UserEmp              NVARCHAR2(60)  NULL ,
	PssEmp               NVARCHAR2(120)  NULL ,
	LevelEmp             NVARCHAR2(60)  NULL ,
    CONSTRAINT CodEmp_PK PRIMARY KEY (CodEmp)
);

CREATE SEQUENCE CodEmp
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CodEmp
BEFORE INSERT ON Empleados
FOR EACH ROW
BEGIN
SELECT CodEmp.NEXTVAL INTO :NEW.CODEMP FROM DUAL;
END;

CREATE OR REPLACE PROCEDURE INSERTEMPLEADO
(
 DniEmpleado NVARCHAR2,
 NomEmpleado NVARCHAR2,
 ApeEmpleado NVARCHAR2,
 EmailEmpleado NVARCHAR2,
 CelEmpleado NUMBER,
 DirecEmpleado NVARCHAR2,
 UserEmpleado NVARCHAR2,
 PssEmpleado NVARCHAR2,
 LevelEmpleado NVARCHAR2
)
IS
BEGIN
  INSERT INTO EMPLEADOS(DniEmp,NomEmp,ApeEmp,EmailEmp,CelEmp,DirecEmp,UserEmp,PssEmp,LevelEmp)
  VALUES (DniEmpleado,NomEmpleado,ApeEmpleado,EmailEmpleado,
          CelEmpleado,DirecEmpleado,UserEmpleado,
          PssEmpleado,LevelEmpleado);
  COMMIT;
END;

BEGIN INSERTEMPLEADO('15796384','EDWIN ERNESTO','ACUÑA TARRILLO','EDWIN@GMAIL.COM','958718625','AV. PAKAMUROS 510','EDWIN','EDWIN','2');END;
BEGIN INSERTEMPLEADO('71448172','ANTONIO ARAVELI','ARAUJO VELIZ','AARAUJO@GMAIL.COM','947888114','SAN CARLOS 1026','71448172','b0481e0f6283b91f6cd4205ad80c58c9','1'); END;
BEGIN INSERTEMPLEADO('71448173','CESAR HERLI','ARAUJO VELIZ','CESAR@GMAIL.COM','947897654','SAN CARLOS 1026','71448173','3b6a87a97835a75fc2bfe0d1c27fc0eb','2'); END;
BEGIN INSERTEMPLEADO('71448173','ROMER EDGARDO','REQUEJO FERNÁNDEZ','ROMER@GMAIL.COM','947897654','SAN CARLOS 1026','71448174','71448174','2'); END;


CREATE VIEW VW_LOGIN
AS
SELECT EMPLEADOS.CODEMP, EMPLEADOS.DNIEMP, EMPLEADOS.USEREMP, EMPLEADOS.PSSEMP, EMPLEADOS.LEVELEMP, CONCAT(CONCAT(EMPLEADOS.NOMEMP,' '), EMPLEADOS.APEEMP) AS IDENTIDAD
        FROM EMPLEADOS;